-- Criação da tabela de histórico de entradas
CREATE TABLE historico_entradas (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  codigo TEXT NOT NULL,
  descricao TEXT,
  fabricante TEXT,
  fornecedor TEXT,
  data_movimento TIMESTAMP WITH TIME ZONE,
  quantidade NUMERIC,
  criado_em TIMESTAMP WITH TIME ZONE DEFAULT NOW()
);

-- Permissões de RLS (Row Level Security) - Permitindo acesso anon e autenticado para simplificar no protótipo
ALTER TABLE historico_entradas ENABLE ROW LEVEL SECURITY;

CREATE POLICY "Permitir leitura pública historico_entradas" 
ON historico_entradas FOR SELECT 
USING (true);

CREATE POLICY "Permitir inserção pública historico_entradas" 
ON historico_entradas FOR INSERT 
WITH CHECK (true);

CREATE POLICY "Permitir atualização pública historico_entradas" 
ON historico_entradas FOR UPDATE 
USING (true);

CREATE POLICY "Permitir deleção pública historico_entradas" 
ON historico_entradas FOR DELETE 
USING (true);
